# This is a basic workflow to help you get started with Actions

name: 萌喵大作战

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 0-12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/NIKE996/ziye1998.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
      - name: '运行 【萌喵大作战】'
        run: |
          cd ~/js   
          node Task/mmdzz.js